name: Build ZCore and Send to Telegram

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Rename BlackBox Package
        run: |
          grep -rl "top.niunaijun.blackbox" . | xargs sed -i 's/top.niunaijun.blackbox/zcore/g'

      - name: Grant Permission
        run: chmod +x gradlew

      - name: Build AAR
        run: ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zcore-aar
          path: "**/*.aar"

      - name: Send AAR to Telegram
        run: |
          FILE=$(find . -name "*.aar" | head -n 1)
          curl -F document=@"$FILE" \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument \
          -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }}
